### ISSUE TITLE
use RoboFont extensions defaults

### ISSUE THREAD

**Issue by typemytype** [jansindl3r/Scale-absolutely#1]
I would not encourage to set and get defaults in a file inside an extension.

use `getExtensionDefault` `setExtensionDefault` to change and 
optionally `registerExtensionDefaults` to register your default keys.

```
scaleAbsolutelyDefaultKey = "jan-sindler.scale.absolutely"

getExtensionDefault(scaleAbsolutelyDefaultKey, fallback=True)

...
setExtensionDefault(scaleAbsolutelyDefaultKey, False

```

see https://robofont.com/documentation/building-tools/api/mojo/mojo-extensions/#mojo.extensions.getExtensionDefault

https://github.com/jansindl3r/Scale-absolutely/blob/191e7b78fe6e399a90edc46f7544050492270877/scaleAbsolutely.robofontExt/lib/scaleAbsolutely.py#L77-L78

**Comment by jansindl3r** [comment]
Alright, thanks. I was thinking about it but didn't know how to do such thing! I will look into it

**Comment by jansindl3r** [comment]
@typemytype done, thanks for the tip!
