### ISSUE TITLE
"Not a valid extension" 

### ISSUE THREAD

**Issue by okay-type** [jansindl3r/Scale-absolutely#2]
This looks neat, but it won't install for me. I get a "Not a valid extension" notification and a traceback: addToMenu is a required info.plist key

**Comment by jansindl3r** [comment]
Hi, thanks a lot for reporting. I didn't have the error :/ now it's fixed. I hope that this inconvenience won't stop you to be an "absolute scaler" :) Please try and close the issue if it's fixed for you as well
