### ISSUE TITLE
Traceback for py3 grep

### ISSUE THREAD

**Issue by okay-type** [jansindl3r/Scale-absolutely#3]
Installing 'Scale, absolutely!' report:
  /Users/k/Library/Application Support/RoboFont/plugins/scaleAbsolutely.robofontExt/lib/tools.py:26: DeprecationWarning: invalid escape sequence \.

making it an r'' string should fix it

pattern = re.compile(r"^([0-9\.]+)+$")

**Comment by jansindl3r** [comment]
@okay-type thanks for reporting! I am in middle of upgrading it. In the coming days I will push upgrade containing this fix as well.

**Comment by jansindl3r** [comment]
fixed and new functionality added in the latest version, thanks again for reporting.
